---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -f colored .
  ansible-lint .
platforms:
  - name: centos-7
    command: ''
    image: geerlingguy/docker-centos7-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
  - name: centos-8
    command: ''
    image: docker-centos8-ansible:latest
    dockerfile: ../default/docker/centos-8/Dockerfile
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-9-sysvinit
    image: docker.io/library/debian:9
  - name: debian-9-systemd
    command: ''
    image: geerlingguy/docker-debian11-ansible:latest
    # dockerfile: ../default/docker/centos-8/Dockerfile
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-10-systemd
    command: ''
    image: geerlingguy/docker-debian11-ansible:latest
    # dockerfile: ../default/docker/centos-8/Dockerfile
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-11-systemd
    command: ''
    image: geerlingguy/docker-debian11-ansible:latest
    # dockerfile: ../default/docker/centos-8/Dockerfile
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
      stdout_callback: yaml
  # create: ../local/create.yml
  # destroy: ../local/destroy.yml
  playbooks:
    converge: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/converge.yml
    prepare: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/prepare.yml
    verify: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/verify.yml
  inventory:
    links:
      # hosts: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/inventory.yml
      group_vars: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/group_vars
      host_vars: ${MOLECULE_PROJECT_DIRECTORY}/molecule/local/host_vars
verifier:
  name: ansible
